### PR TITLE
Feature Highlight and comment #164489763

### PR DESCRIPTION
**Pull request by jnkindi**
#### What does this PR do?
- This PR enables users to highlight a specific word or sentence in an article and add a comment
#### Description of Task to be completed?
- user is able to highlight a specific word or sentence
- user is able to add a comment on the highlighted section
- user is able to access all his/her highlights on an article
- user is able to share highlighted section on twitter and facebook
- user is able to easly copy selected highlight
#### How should this be manually tested?
 - by visiting a specific article
#### Any background context you want to provide?
- none
#### What are the relevant pivotal tracker stories?
- # 164489763
#### Screenshots (if appropriate)
Screen Shot 2019-06-16 at 23 12 31
Screen Shot 2019-06-16 at 23 11 59
Screen Shot 2019-06-16 at 23 12 17

#### Questions:
- None

### CODE REVIEW

**Review by frankhn — CHANGES_REQUESTED** [review]
Thanks for your hard work @jnkindi. I would like to say that it's a good practice to not neglect the sentence case when it comes to UI/UX. like in src/components/form.jsx line 149. I also noticed that you're actions seems to be in helpers, for the sake of following the same folder structure as a team, these should be in redux/actions. likewise in "src/services/login.service.js" you should add a backslash cause in the .env there is no backslash on the REACT_APP_URL for the rest of the team. Thanks for your consideration.

**Comment by jnkindi** [comment]
> Thanks for your hard work @jnkindi. I would like to say that it's a good practice to not neglect the sentence case when it comes to UI/UX. like in src/components/form.jsx line 149. I also noticed that you're actions seems to be in helpers, for the sake of following the same folder structure as a team, these should be in redux/actions. likewise in "src/services/login.service.js" you should add a backslash cause in the .env there is no backslash on the REACT_APP_URL for the rest of the team. Thanks for your consideration.

Hello Frank, I have implemented the requested changes except moving my file into actions because it is a helper. It helps in highlighting articles content.

**Review by frankhn — APPROVED** [review]
LGTM

**Review by mystere10 — COMMENTED** [review]
Good job, i tested this endpoint, it works fine but As this endpoint has no tests you should write the reason why in the PR description

**Pull request merged**
