### PR TITLE
#164489749 User should be able to rate article

### PR DESCRIPTION
**Pull request by frankhn**
#### What does this PR do?
 This PR adds a feature to allow users to rate articles
#### Description of Task to be completed?

- [x] Integrating emojis for rating
- [x] Styling the emojis
- [x] Integrating the rating component to the read article page
- [x] Styling the rating button on the read article page.
- [x] Testing the functionality, behaviors, and connectivity to the backend.
- [x] Testing the Average rating component.
- [x] Testing redux actions and reducers

#### How should this be manually tested?

- This can be tested by visiting a single article page then you should see a button to rate the article.

#### What are the relevant pivotal tracker stories?

- https://www.pivotaltracker.com/story/show/164489749

#### Screenshots (if appropriate).
image
image
image

### CODE REVIEW

**Review by mystere10 — COMMENTED** [review]
Thanks for this feature @frankhn, i would like you to upload images of your feature so i can know what is going on here thx. Consider uploading images of how your feature works

**Review by mwibutsa — APPROVED** [review]

**Review by mwibutsa — CHANGES_REQUESTED** [review]
Would you like to add a ```/``` in front of  ``` api/articles/${slug}/rate/${rate} so that it will be easier for all of us to use the same environment variable? , me, innocent, Jack and @Inclet  are adding a slash

**Comment by frankhn** [comment]
> Would you like to add a `/` in front of ``` api/articles/${slug}/rate/${rate} so that it will be easier for all of us to use the same environment variable? , me, innocent, Jack and @Inclet are adding a slash

Thanks for your feedback @mwibutsa. so far I would like to let you know that I have added the backslash on the call of that endpoint. Thanks for reminding me that.

**Review by mwibutsa — APPROVED** [review]
LGTM

**Pull request merged**
