### PR TITLE
#164489741 SASS processing

### PR DESCRIPTION
**Pull request by jnkindi**
#### What does this PR do?
- This PR allows processing of .scss to .css for them to be used
#### Description of Task to be completed?
- I installed node-saas package for allowing the processing of scss file.
- I created a folder of styles in src with two subfolders for scss files and css for the processed scss.
- I added script **scss** for processing all scss files
- I added script **scss:watch** for processing scss file as you continue developing
#### How should this be manually tested?
- by command running `npm run scss`
- by command running `npm run scss:watch`
#### Any background context you want to provide?
- None
#### What are the relevant pivotal tracker stories?
-   # 164489741
#### Screenshots (if appropriate)
-  None

### CODE REVIEW

**Review by frankhn — COMMENTED** [review]
Looks good to me. good job @jnkindi, though this PR has to wait for the chore to set up the test environment to be done raised and merged.
thanks.

**Comment by mwibutsa** [comment]
Let's wait for the chore of setting up tests and see if it passes after rebasing

**Comment by istafrica-dennw** [comment]
@jnkindi I hope you have realized that tests are failing before we go for merging.

**Comment by jnkindi** [comment]
> @jnkindi I hope you have realized that tests are failing before we go for merging.

Thanks for your review. There was an issue that was solved in the PR raised by @mystere10 . I am rebasing it.

**Comment by istafrica-dennw** [comment]
> > @jnkindi I hope you have realized that tests are failing before we go for merging.
> 
> @denislohan I have to rebase. because the issue was solved in the PR raised by @mystere10
So do it because I merged everything else

**Comment by jnkindi** [comment]
@denislohan The PR is now ready to be merged.

**Review by mwibutsa — APPROVED** [review]
Great Job I can't wait to get it merged!

**Comment by istafrica-dennw** [comment]
@frankhn  have you rebased?

**Comment by jnkindi** [comment]
> @frankhn have you rebased?

@denislohan It is my PR. I have rebased.

**Review by mystere10 — APPROVED** [review]
Good job jack!

**Comment by istafrica-dennw** [comment]
@frankhn humbly rebase as I am done merging jack and I merge your commit

**Pull request merged**
