### PR TITLE
Chore  #166054861 Setup testing environment and project folder structure

### PR DESCRIPTION
**Pull request by mystere10**
**What does this PR do**
This PR solves the testing environment problem and project folder structure

**Description of Task to be completed**
- After the continuous integration was set the built failed so this PR sets new tests folder where all tests will be added 
- It creates folders for actions and actions types to separate them

**How should this be manually tested**
This can be tested by running `npm test`

**Any background context you want to provide**
Before the build was failing

**What are the relevant pivotal tracker stories**
[Chore #166054861]

### CODE REVIEW

**Review by mwibutsa — APPROVED** [review]
Thank you as I can see the test are running

**Review by frankhn — COMMENTED** [review]
Looks good to me. good job @mystere10.

**Comment by jnkindi** [comment]
Looks good.
Great work @mystere10

**Review by jnkindi — APPROVED** [review]

**Comment by istafrica-dennw** [comment]
@mystere10  tell the people to rebase the changes

**Pull request merged**
